# Generated by Django 5.1.4 on 2025-04-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='userContent.replies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'likes',
                'unique_together': {('user', 'reply')},
            },
        ),
    ]
