# Generated by Django 5.1.4 on 2025-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userContent', '0003_remove_profile_birth_date_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, default="<django.db.models.query_utils.DeferredAttribute object at 0x000001397047E010> hasn't added a biography yet.", max_length=500),
        ),
    ]
