# Generated by Django 5.1.4 on 2025-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userContent', '0004_alter_profile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, default="This user hasn't added a biography yet.", max_length=500),
        ),
    ]
