# Generated by Django 5.1.4 on 2025-04-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userContent', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/default.jpg', null=True, upload_to='media/avatars/'),
        ),
    ]
